### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by top4ek** [tarantool/tarantool-ruby#24]
Space:
```
localhost:33011> box.space.urls
---
- index:
    0: &0
      unique: true
      parts:
      - type: string
        fieldno: 1
      id: 0
      space_id: 515
      name: primary
      type: TREE
    primary: *0
  on_replace: 'function: 0x40e20390'
  temporary: false
  id: 515
  engine: vinyl
  enabled: true
  name: urls
  field_count: 0
...
```
Now we can connect to server and it's fine:
```
~ tarantoolctl connect 33011
symbol count is 0
no symbols found in /usr/bin/tarantool
connected to localhost:33011
localhost:33011> box.space.urls:select{'113'}
---
- []
...

localhost:33011> box.space.urls:insert{'113'}
---
- ['113']
...

localhost:33011> box.space.urls:select{'113'}
---
- - ['113']
...
```

Now we try to do the same but with ruby.
1. i have localhost definition in my /etc/hosts, but:
```
2.3.1 :001 > require 'tarantool16'
 => true 
2.3.1 :002 > db = Tarantool16.new host:'localhost:33011'    
Errno::EAFNOSUPPORT: Address family not supported by protocol - connect(2) for [::1]:33011
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/connection/dumb.rb:82:in `connect'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/connection/dumb.rb:82:in `_connect'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/connection/dumb.rb:18:in `initialize'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:12:in `new'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:12:in `initialize'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16.rb:24:in `new'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16.rb:24:in `new'
        from (irb):2
        from /home/alex/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```
2. I can connect via supplying IP address:
```
2.3.1 :003 > db = Tarantool16.new host:'127.0.0.1:33011'        
 => #<Tarantool16::DumbDB:0x00000001e744c8 @host=["tcp", "127.0.0.1:33011"], @opts={:host=>"127.0.0.1:33011"}, @future=nil, @spaces=nil, @defined_fields={}, @conn=#<Tarantool16::Connection::Dumb:0x00000001e76340 @host=["tcp", "127.0.0.1:33011"], @user=nil, @reconnect_timeout=0.2, @reconnect=true, @timeout=nil, @p=#<MessagePack::Packer:0x00000001e6ff90>, @u=#<MessagePack::Unpacker:0x00000001e6fec8>, @s=0, @reconnect_time=872.758065964, @socket=#<Socket:fd 7>, @retry=true, @nbuf="\x00\x00\x00\x00\x00", @greeting="Tarantool 1.7.3 (Binary) 59328fa6-5661-4557-a86e-d7219cd0d6a2  \n", @salt="\xFE}K\x9C!e\x9ASE\xDCo\e\xD6\x1E\x16\x12?\\\xD3\xCC">> 
```
3. Now i try to select:
```
2.3.1 :004 > db.select(:urls, '113')
NoMethodError: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/schema.rb:36:in `block in fields='
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/schema.rb:21:in `each'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/schema.rb:21:in `each_with_index'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/schema.rb:21:in `fields='
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/schema.rb:10:in `initialize'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:99:in `new'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:99:in `block in _fill_spaces'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:97:in `each'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:97:in `_fill_spaces'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:70:in `block (3 levels) in _space_future'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:81:in `_synchronized'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:69:in `block (2 levels) in _space_future'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/connection/dumb.rb:37:in `send_request'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/connection/common.rb:198:in `_select'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:169:in `_select'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:90:in `block in _space_future'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:81:in `_synchronized'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:57:in `_space_future'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:36:in `_with_space'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:171:in `_select'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:25:in `select'
        from (irb):4
        from /home/alex/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```
And then if I repeat same command getting strange reply:
```
2.3.1 :005 > db.select(:urls, '113')
 => #<Proc:0x00000001dd6570@/home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:118 (lambda)> 
```
After that if I pass any command I get following(this is normal at this time as i know)
```
2.3.1 :006 > db.insert(:urls, '234')        
RuntimeError: Blocking future accepts only 1 callback
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:116:in `then_blk'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:37:in `_with_space'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/db.rb:127:in `_insert'
        from /home/alex/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.0/lib/tarantool16/dumb_db.rb:38:in `insert'
        from (irb):6
        from /home/alex/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :007 > 
```
So if I restart ruby instance I'm able to connect but can't query or insert smth.
If i do `db.select('urls', '113')` right after connection(passing string, not symbol) I get `lambda` as earlier.

**Comment by funny-falcon** [comment]
Please, can you do three things:
1. paste config.lua that is necessary for bug reproduction,
2. paste `box.space._vspace:select()`
3. add `p fld` to schema.rb above line 36.

**Comment by funny-falcon** [comment]
No further help for me?

I believe, you have "field" declaration in space, which misses "name". Is it true?

**Comment by top4ek** [comment]
Sorry for delay, had no time yesterday :(
Yes, my fault. I've have wrong format.
```
urls = box.schema.space.create('urls', { engine = 'vinyl',
        format = {
          [1] = {['url'] = 'string'},
        }
      }
    )
    urls:create_index('primary', {type = 'tree', parts = {1, 'string'}})
```
Gives `_vspace` `- [515, 1, 'urls', 'vinyl', 0, {}, [{'url': 'string'}]`
But now i've changed to 
```
urls = box.schema.space.create('urls', { engine = 'vinyl', {
       format = { [1] = { name = 'url', type = 'string'} }
     }
   }
)
urls:create_index('primary', {type = 'tree', parts = {1, 'string'}})
```
Gives `_vspace` `[515, 1, 'urls', 'vinyl', 0, {}, [{'name': 'url', 'type': 'string'}]]`
2.3.1 :003 > db.select(:urls, '113')
{"type"=>"str", "name"=>"key"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"engine", "type"=>"str"}
{"name"=>"field_count", "type"=>"num"}
{"name"=>"flags", "type"=>"str"}
{"name"=>"format", "type"=>"*"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"engine", "type"=>"str"}
{"name"=>"field_count", "type"=>"num"}
{"name"=>"flags", "type"=>"str"}
{"name"=>"format", "type"=>"*"}
{"name"=>"id", "type"=>"num"}
{"name"=>"iid", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"type", "type"=>"str"}
{"name"=>"opts", "type"=>"array"}
{"name"=>"parts", "type"=>"array"}
{"name"=>"id", "type"=>"num"}
{"name"=>"iid", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"type", "type"=>"str"}
{"name"=>"opts", "type"=>"array"}
{"name"=>"parts", "type"=>"array"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"setuid", "type"=>"num"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"setuid", "type"=>"num"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"type", "type"=>"str"}
{"name"=>"auth", "type"=>"*"}
{"name"=>"id", "type"=>"num"}
{"name"=>"owner", "type"=>"num"}
{"name"=>"name", "type"=>"str"}
{"name"=>"type", "type"=>"str"}
{"name"=>"auth", "type"=>"*"}
{"name"=>"grantor", "type"=>"num"}
{"name"=>"grantee", "type"=>"num"}
{"name"=>"object_type", "type"=>"str"}
{"name"=>"object_id", "type"=>"num"}
{"name"=>"privilege", "type"=>"num"}
{"name"=>"grantor", "type"=>"num"}
{"name"=>"grantee", "type"=>"num"}
{"name"=>"object_type", "type"=>"str"}
{"name"=>"object_id", "type"=>"num"}
{"name"=>"privilege", "type"=>"num"}
{"name"=>"id", "type"=>"num"}
{"name"=>"uuid", "type"=>"str"}
{"id"=>"integer"}
NoMethodError: undefined method `to_sym' for nil:NilClass
```

**Comment by funny-falcon** [comment]
ok, I understand. This place should be sanity checked.
But I'm in doubt what to do: ignore whole name fields for such table, even if some correct?
What do you think?

**Comment by top4ek** [comment]
I beleive some error reporting must be added :)

**Comment by funny-falcon** [comment]
Added workaround for malformed field definitions.
