### ISSUE TITLE
Address family not supported by protocol family - connect(2) for [::1]:33013

### ISSUE THREAD

**Issue by noff** [tarantool/tarantool-ruby#25]
I run docker container with tarantool 1.7.
I've exposed port 33013 and it works:

```
✗ telnet 127.0.0.1 33013
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Tarantool 1.7.5 (Binary) 8b1fda00-2ea9-496c-9373-e5beca5dcb82  
FjglYx5rTx0EFwAjd8kUFoQY9InJ+EgGCS27dZdluwI=                   

```

When I try to 
```
Tarantool16.new host:'localhost:33013'
```

And get error:

```
Errno::EAFNOSUPPORT: Address family not supported by protocol family - connect(2) for [::1]:33013
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:82:in `connect'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:82:in `_connect'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:18:in `initialize'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `new'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `initialize'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
	from (irb):8
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/mkechinov/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

Rails 4.2.6
Ruby 2.3.1

**Comment by noff** [comment]
Just change localhost to 127.0.0.1 and everything works.
