### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by narsariusv** [tarantool/tarantool-ruby#27]
Hope all is well! Having issues connecting.

System - Ubuntu Server 18.04.2 LTS

`require 'tarantool16'

db = Tarantool16.new host:'localhost:3301', user:'user', password:'secret'
`
Returns:
`Traceback (most recent call last):
        7: from test.rb:3:in `<main>'
        6: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
        5: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
        4: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `initialize'
        3: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `new'
        2: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:18:in `initialize'
        1: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:82:in `_connect'
/var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:82:in `connect': Address family not supported by protocol - connect(2) for [::1]:3301 (Errno::EAFNOSUPPORT)`

Have also tried '127.0.0.1' with the return:
`Traceback (most recent call last):
        7: from test.rb:3:in `<main>'
        6: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
        5: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16.rb:24:in `new'
        4: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `initialize'
        3: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/db.rb:12:in `new'
        2: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:18:in `initialize'
        1: from /var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:66:in `_connect'
/var/lib/gems/2.5.0/gems/tarantool16-0.1.1/lib/tarantool16/connection/dumb.rb:104:in `rescue in _connect': Connection refused - connect(2) for 127.0.0.1:3301 (Tarantool16::Connection::CouldNotConnect)
`

**Comment by funny-falcon** [comment]
And why you asking me?

I don't remember, where should be ipv6 enabled. Perhaps, it is issue of the library, but probably of your host as well.

But second error is clearly tells there is no tarantool running on port 3301 of localhost.
